name: Build and publish Docker images

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      image_name_lower: ${{ steps.lowercase.outputs.image_name_lower }}
    steps:
      - name: Convert repository name to lowercase
        id: lowercase
        shell: bash
        run: |
          echo "image_name_lower=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "image_name_lower=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  build-frontend:
    needs: set-vars
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.set-vars.outputs.image_name_lower }}/frontend

      - name: Build and push frontend image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./devops/frontend.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache-frontend-amd64
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend-amd64,mode=max

  build-backend:
    needs: set-vars
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.set-vars.outputs.image_name_lower }}/backend

      - name: Build and push backend image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./devops/backend.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache-backend-amd64
          cache-to: type=local,dest=/tmp/.buildx-cache-backend-amd64,mode=max
